application: recipe-app
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /recipes
  static_dir: recipes
  application_readable: true

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
