version: 2.1

executors:
  node-executor:
    docker:
      - image: node:latest

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
